name: Create git badges
on:
  push:
    branches:
      - main
jobs:
  badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: badge
        uses: doapply/action-badge@2.1.0
        with:
          badge_id: ${{ secrets.badge_ID }}

